# Generated by Django 5.0.1 on 2024-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='pod_prod',
            field=models.CharField(max_length=200),
        ),
    ]
