# Generated by Django 3.2.12 on 2024-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240411_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pic',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
    ]
